server.port=8080
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
#eureka.instance.hostname=eureka-server
eureka.instance.prefer-ip-address=true
app.eureka-server=eureka-server
#management.zipkin.tracing.endpoint=http://zipkin:9411
