---
version: '3'
services:
  ## Eureka Server
  eureka-server:
    image: dev-challenge/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ## API Gateway
  api-gateway:
    image: dev-challenge/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server

  ## Compiler-Service Docker Compose Config
  compiler-service:
    container_name: compiler-service
    image: dev-challenge/compiler:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - api-gateway

  ## Translator-Service Docker Compose Config
  translator-service:
    container_name: translator-service
    image: dev-challenge/translator:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - application.executing-endpoint=https://libretranslate.de
    depends_on:
      - eureka-server
      - api-gateway

  ## React UI Application Docker Compose Config
  ui-service:
    image: dev-challenge/ui
    container_name: ui-service
    build: ../../frontend/dev-challenge
    ports:
      - "80:3000"
    depends_on:
      - compiler-service
      - translator-service